development:
  port: 9312
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
test:
  port: 8444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
staging:
  port: 7444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
pre_production:
  port: 6444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
production:
  port: 5444
  pid_file: log/searchd.pid
  searchd_log_file: "log/searchd.log"
  query_log_file: "log/searchd_query.log"
  pid_file: "log/searchd.pid"
  max_matches: 100000
  mem_limit: 128M
  